version: '3.8'

services:
  async-rust-icmp:
    image: traceroute-rust
    container_name: traceroute-rust
    command:
      - google.com
    cap_add:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: 1.0