version: '3.8'

services:
  async-traceroute:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: async-traceroute
    command:
      - google.com
    cap_add:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: 1.0